package com.cwilliams.chipdog.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006b5e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF44fce4)
val md_theme_light_onPrimaryContainer = Color(0xFF00201b)
val md_theme_light_secondary = Color(0xFF5356a9)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe0e0ff)
val md_theme_light_onSecondaryContainer = Color(0xFF0a0764)
val md_theme_light_tertiary = Color(0xFF5c2bff)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFe6deff)
val md_theme_light_onTertiaryContainer = Color(0xFF180065)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1f1a1b)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1f1a1b)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFfaeeef)
val md_theme_light_inverseSurface = Color(0xFF352f30)
val md_theme_light_inversePrimary = Color(0xFF00dfc8)

val md_theme_dark_primary = Color(0xFF000000)
val md_theme_dark_onPrimary = Color(0xFF003730)
val md_theme_dark_primaryContainer = Color(0xFF005046)
val md_theme_dark_onPrimaryContainer = Color(0xFF44fce4)
val md_theme_dark_secondary = Color(0xFFbfc1ff)
val md_theme_dark_onSecondary = Color(0xFF232578)
val md_theme_dark_secondaryContainer = Color(0xFF3a3d8f)
val md_theme_dark_onSecondaryContainer = Color(0xFFe0e0ff)
val md_theme_dark_tertiary = Color(0xFFc9beff)
val md_theme_dark_onTertiary = Color(0xFF2c009f)
val md_theme_dark_tertiaryContainer = Color(0xFF4000dc)
val md_theme_dark_onTertiaryContainer = Color(0xFFe6deff)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1D1D1D)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF1D1D1D)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF070707)
val md_theme_dark_onSurfaceVariant = Color(0xFFFFFFFF)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1f1a1b)
val md_theme_dark_inverseSurface = Color(0xFFebe0e1)
val md_theme_dark_inversePrimary = Color(0xFF006b5e)